### ISSUE TITLE
Failed to load the rails-model-schema package

### ISSUE THREAD

**Issue by liveact** [platanus/atom-rails-model-schema#15]
[Enter steps to reproduce below:]

1. After update
2. On Atom launche

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [rails-model-schema](https://github.com/platanus/atom-rails-model-schema) package, v0.7.1

### Stack Trace

Failed to load the rails-model-schema package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mads-air/.atom/packages/rails-model-schema/node_modules/pathwatcher/lib/file.js:10:7)
    at Object.<anonymous> (/Users/mads-air/.atom/packages/rails-model-schema/node_modules/pathwatcher/lib/file.js:551:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -0:03.6.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
rails-i18n, v0.1.3
rails-model-schema, v0.7.1

# Dev
No dev packages
```

**Comment by vanboom** [comment]
I am also now seeing this error on atom 1.35.0x64

Line number: 2
'octicons.less' wasn't found. Tried - ...
