### ISSUE TITLE
cannot Install

### ISSUE THREAD

**Issue by edyywang** [platanus/atom-rails-model-schema#17]
> runas@3.1.1 install /private/var/folders/w5/n6_py91d0hq4h4zsc6s29k7c0000gn/T/apm-install-dir-11607-27172-q1i8m9/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/w5/n6_py91d0hq4h4zsc6s29k7c0000gn/T/apm-install-dir-11607-27172-q1i8m9/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/edyywang/.atom/.apm/.apmrc" "--userconfig" "/Users/edyywang/.atom/.apmrc" "install" "/private/var/folders/w5/n6_py91d0hq4h4zsc6s29k7c0000gn/T/d-11607-27172-1f8cr4i/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/w5/n6_py91d0hq4h4zsc6s29k7c0000gn/T/apm-install-dir-11607-27172-q1i8m9/npm-debug.log

**Comment by JustinAiken** [comment]
Seeing something similar:

```
Error deactivating package 'rails-model-schema' TypeError: Cannot read property 'deactivateCurrentEditors' of undefined
    at Object.module.exports.RailsModelSchema.deactivate (/Users/jaiken/.atom/packages/rails-model-schema/lib/rails-model-schema.coffee:31:12)
    at Package.module.exports.Package.deactivate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:647:21)
    at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:595:12)
    at PackageManager.module.exports.PackageManager.update (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:366:23)
    at PackageCard.module.exports.PackageCard.update (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:656:34)
    at HTMLButtonElement.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:300:24)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
Updating package rails-model-schema to vnull failed Error: Updating to “rails-model-schema@0.7.3” failed.
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:396:21
    at exit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12) 
> runas@3.1.1 install /private/var/folders/ym/spr3gnrj0h52wvp16x9xnfbw7jvl0l/T/apm-install-dir-116027-2588-sy03w9/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild


make: *** No rule to make target `../../../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/ym/spr3gnrj0h52wvp16x9xnfbw7jvl0l/T/apm-install-dir-116027-2588-sy03w9/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jaiken/.atom/.apm/.apmrc" "--userconfig" "/Users/jaiken/.atom/.apmrc" "install" "/private/var/folders/ym/spr3gnrj0h52wvp16x9xnfbw7jvl0l/T/d-116027-2588-4jkhg8/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/ym/spr3gnrj0h52wvp16x9xnfbw7jvl0l/T/apm-install-dir-116027-2588-sy03w9/npm-debug.log
```

The referenced `npm-debug.log` doesn't seem to be there.  I'm on 1.5.0beta-1 (same err with beta-0)

**Comment by steakknife** [comment]
```
$ apm-beta install rails-model-schema
Installing rails-model-schema to {{redacted}}/.atom/packages ✗

> runas@3.1.1 install /private/var/folders/pd/hw84_23143bdr0hrfwnx2lc00000gn/T/apm-install-dir-116920-50152-tti2dp/node_modules/rails-model-schema/node_modules/runas
> node-gyp rebuild

/private/var/folders/pd/hw84_23143bdr0hrfwnx2lc00000gn/T/apm-install-dir-116920-50152-tti2dp
└── (empty)


make: *** No rule to make target `../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/pd/hw84_23143bdr0hrfwnx2lc00000gn/T/apm-install-dir-116920-50152-tti2dp/node_modules/rails-model-schema/node_modules/runas
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/pd/hw84_23143bdr0hrfwnx2lc00000gn/T/apm-install-dir-116920-50152-tti2dp/package.json'
npm WARN apm-install-dir-116920-50152-tti2dp No description
npm WARN apm-install-dir-116920-50152-tti2dp No repository field.
npm WARN apm-install-dir-116920-50152-tti2dp No README data
npm WARN apm-install-dir-116920-50152-tti2dp No license field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "{{redacted}}/.atom/.apm/.apmrc" "--userconfig" "{{redacted}}/.atom/.apmrc" "install" "/private/var/folders/pd/hw84_23143bdr0hrfwnx2lc00000gn/T/d-116920-50152-farv2p/package.tgz" "--runtime=electron" "--target=1.3.6" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/pd/hw84_23143bdr0hrfwnx2lc00000gn/T/apm-install-dir-116920-50152-tti2dp/npm-debug.log
npm ERR! code 1
```
