### ISSUE TITLE
Can't Install (just an fyi)

### ISSUE THREAD

**Issue by lankford** [platanus/atom-rails-model-schema#23]
Installing “rails-model-schema@0.7.3” failed.Hide output…

> runas@3.1.1 install /private/var/folders/0r/hkmtj2m12g34k9r1sw3c7v540000gn/T/apm-install-dir-116416-20623-14d6ajw/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:119:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/0r/hkmtj2m12g34k9r1sw3c7v540000gn/T/apm-install-dir-116416-20623-14d6ajw/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mattlankford/.atom/.apm/.apmrc" "--userconfig" "/Users/mattlankford/.atom/.apmrc" "install" "/private/var/folders/0r/hkmtj2m12g34k9r1sw3c7v540000gn/T/d-116416-20623-1bg4i0s/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/0r/hkmtj2m12g34k9r1sw3c7v540000gn/T/apm-install-dir-116416-20623-14d6ajw/npm-debug.log

NOTE : the above file was not on my system... sorry about that..

**Comment by lacostenycoder** [comment]
Error indicates your current Python version is not supported.  I had the same issue and solved it by using a supported version with https://github.com/pyenv/pyenv
